---
training:
  n_epochs: !!int 1             # number of epochs
  batch_size: !!int 512         # batch size
  optimizer: !!str "RMSprop"    # optimizer
  learning_rate_scheduler:      # learning rate schedulers
    - FixLR:
        lr_lambda: !!str "lambda _: 1.0"
    - LinearLR:
        start_factor: !!float 1.0      
        end_factor: !!float 0.1
        total_iters: !!int 100 
    - OneCycleLR:
        max_lr: !!float 0.1
        pct_start: !!float 0.05
        steps_per_epoch: !!int 10
        epochs: !!int 10
    - CyclicLR:
        base_lr: !!float 0.001
        max_lr: !!float 0.1
        step_size_up: !!int 5
        mode: !!str "triangular"
    - CyclicLR:
        base_lr: !!float 0.001
        max_lr: !!float 0.1
        step_size_up: !!int 5
        mode: !!str "triangular2"


CIFAR10:
  loss: !!str "CrossEntropy"  # loss
  SGD:
    lr: !!float 0.01          # learning rate
  RMSprop:
    lr: !!float 0.1
    momentum: !!float 0.9
    weight_decay: !!float 1e-5
