---
training:
  n_epochs: !!int 150             # number of epochs
  batch_size: !!int 4096         # batch size
  optimizer: !!str "RMSprop"    # optimizer

CIFAR10:
  loss: !!str "CrossEntropy"  # loss
  RMSprop:
    lr: !!float 9.5e-4
    momentum: !!float 0.9
    weight_decay: !!float 1e-5
  learning_rate_scheduler:      # learning rate schedulers
    FixLR:
      lr_lambda: !!str "lambda _: 1.0"
    LinearLR:
      start_factor: !!float 1.0
      end_factor: !!float 0.25
      total_iters: !!int 1950 
    OneCycleLR:
      max_lr: !!float 9.5e-4
      pct_start: !!float 0.13
      total_steps: !!int 1950
    CyclicLR:
      base_lr: !!float 2.375e-4
      max_lr: !!float 9.5e-4
      step_size_up: !!int 65
      mode: !!str "triangular"
    CyclicLR2:
      base_lr: !!float 2.375e-4
      max_lr: !!float 9.5e-4
      step_size_up: !!int 5
      mode: !!str "triangular2"


FashionMNIST:
  loss: !!str "CrossEntropy"  # loss
  RMSprop:
    lr: !!float 3e-4
    momentum: !!float 0.9
    weight_decay: !!float 1e-5
  learning_rate_scheduler:      # learning rate schedulers
    FixLR:
      lr_lambda: !!str "lambda _: 1.0"
    LinearLR:
      start_factor: !!float 1.0      
      end_factor: !!float 0.1
      total_iters: !!int 100 
    OneCycleLR:
      max_lr: !!float 3e-4
      pct_start: !!float 0.05
      total_steps: !!int 1831
    CyclicLR:
      base_lr: !!float 5e-5
      max_lr: !!float 3e-4
      step_size_up: !!int 5
      mode: !!str "triangular"
    CyclicLR2:
      base_lr: !!float 5e-5
      max_lr: !!float 3e-4
      step_size_up: !!int 5
      mode: !!str "triangular2"
