---
training:
  n_epochs: !!int 1        # number of epochs
  batch_size: !!int 128       # batch size
  optimizer: !!str "SGD"    # optimizer

CIFAR10:
  loss: !!str "CrossEntropy"       # loss
  SGD:
    lr: !!float 0.01     # learning rate
